project:
  type: website
  output-dir: docs

website:
    title: "Lily Cook"
    navbar:
     left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: BlogPosts.qmd 
        text: Blog
     right:
      - icon: github
        href:  https://github.com/lilypcook/lab-3
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/lilypaintoncook/
        aria-label: LinkedIn
    favicon: "media/flower-icon.jpg"
  
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

